# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17e704d5ad56aab5881c7ea93f34d5c7b39e72abad0aa114413c01774904d892fa8dea29d37f0ee6e3ca2ae8dc0cbb68e45e8078cf01d67c3f33bb55590fb70a

test:
  secret_key_base: 2e90ea5b5aef0da2f89781fc0e9416c4cb109d8e1bfb5e20793de73c4c63a6040cfca76d5a2c30bae849a6b6f4de9b062b4eca05204ee43e5ab4743693612137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
